//TODO jfarina group them by module/UC/whatever to simplify implementation of a shortcuts configuration

//Auth
export const SIGNIN_USER = 'signin_user';
export const SIGNIN_USER_SUCCESS = 'signin_user_success';
export const SIGNOUT_USER = 'signout_user';
export const SIGNOUT_USER_SUCCESS = 'signout_user_success';
export const GET_USER = 'get_user';
export const GET_USER_SUCCESS = 'get_user_success';
export const GET_PERMISSIONS = 'get_permissions';
export const GET_PERMISSIONS_SUCCESS = 'get_permissions_success';

//Common
export const SHOW_LOADER = 'show_loader';
export const HIDE_LOADER = 'hide_loader';
export const SHOW_ERROR = 'show_error';
export const CLEAR_ERROR = 'clear_error';
export const SHOW_MESSAGE = 'show_message';
export const CLEAR_MESSAGE = 'clear_message';

//Client
export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const SEARCH_CLIENTS = 'SEARCH_CLIENTS';
export const SEARCH_CLIENTS_SUCCESS = 'SEARCH_CLIENTS_SUCCESS';
export const CONFIRMATION_CLIENT = 'CONFIRMATION_CLIENT';
export const CONFIRMATION_CLIENT_SUCCESS = 'CONFIRMATION_CLIENT_SUCCESS';

//Voucher type
export const GET_VOUCHER_TYPE = 'GET_VOUCHER_TYPE';
export const GET_VOUCHER_TYPE_SUCCESS = 'GET_VOUCHER_TYPE_SUCCESS';
export const GET_VOUCHER_TYPE_BY_USER = 'GET_VOUCHER_TYPE_BY_USER';
export const GET_VOUCHER_TYPE_BY_USER_SUCCESS = 'GET_VOUCHER_TYPE_BY_USER_SUCCESS';

//Voucher
export const GET_CONFIG_VOUCHER = 'GET_CONFIG_VOUCHER';
export const GET_CONFIG_VOUCHER_SUCCESS = 'GET_CONFIG_VOUCHER_SUCCESS';
export const GET_VOUCHER_HEAD = 'GET_VOUCHER_HEAD';
export const GET_VOUCHER_HEAD_SUCCESS = 'GET_VOUCHER_HEAD_SUCCESS';
export const VOUCHER_HEAD_AUTO = 'VOUCHER_HEAD_AUTO';
export const VOUCHER_HEAD_AUTO_SUCCESS = 'VOUCHER_HEAD_AUTO_SUCCESS';
export const VOUCHER_HEAD_VALIDATE_KEY = 'VOUCHER_HEAD_VALIDATE_KEY';
export const VOUCHER_HEAD_VALIDATE_KEY_SUCCESS = 'VOUCHER_HEAD_VALIDATE_KEY_SUCCESS';
export const VOUCHER_HEAD_CHECK_DATE = 'VOUCHER_HEAD_CHECK_DATE';
export const VOUCHER_HEAD_CHECK_DATE_SUCCESS = 'VOUCHER_HEAD_CHECK_DATE_SUCCESS';

//Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const GET_PRICE_BY_PRODUCT = 'GET_PRICE_BY_PRODUCT';
export const GET_PRICE_BY_PRODUCT_SUCCESS = 'GET_PRICE_BY_PRODUCT_SUCCESS';
export const CHECK_ITEM_BY_PRODUCT = 'CHECK_ITEM_BY_PRODUCT';
export const CHECK_ITEM_BY_PRODUCT_SUCCESS = 'CHECK_ITEM_BY_PRODUCT_SUCCESS';
export const SET_TABLE_DATA_PRODUCTS = 'SET_TABLE_DATA_PRODUCTS';
export const GET_PRODUCTS_CART = 'GET_PRODUCTS_CART';
export const GET_PRODUCTS_CART_SUCCESS = 'GET_PRODUCTS_CART_SUCCESS';
export const SET_INPUT_FOCUS = 'SET_INPUT_FOCUS';
export const SET_INPUT_FOCUS_SUCCESS = 'SET_INPUT_FOCUS_SUCCESS';
export const GET_PRODUCTS_INVOLVEMENT = 'GET_PRODUCTS_INVOLVEMENT';
export const GET_PRODUCTS_INVOLVEMENT_SUCCESS = 'GET_PRODUCTS_INVOLVEMENT_SUCCESS';

//Load Items
export const GET_LOAD_ITEMS = 'GET_LOAD_ITEMS';
export const GET_LOAD_ITEMS_SUCCESS = 'GET_LOAD_ITEMS_SUCCESS';

//Sales affected
export const SALES_AFFECTED_VALIDATE = 'SALES_AFFECTED_VALIDATE';
export const SALES_AFFECTED_VALIDATE_SUCCESS = 'SALES_AFFECTED_VALIDATE_SUCCESS';
export const SALES_AFFECTED_QUANTITY = 'SALES_AFFECTED_QUANTITY'
export const SALES_AFFECTED_QUANTITY_SUCCESS = 'SALES_AFFECTED_QUANTITY_SUCCESS';
export const SALES_AFFECTED_SUB_CALCULATION = 'SALES_AFFECTED_SUB_CALCULATION';
export const SALES_AFFECTED_SUB_CALCULATION_SUCCESS = 'SALES_AFFECTED_SUB_CALCULATION_SUCCESS';
export const SALES_AFFECTED_CONFIRM = 'SALES_AFFECTED_CONFIRM';
export const SALES_AFFECTED_CONFIRM_SUCCESS = 'SALES_AFFECTED_CONFIRM_SUCCESS';